# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(392, 540)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 110, 371, 421))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.updateIDNumber = QtWidgets.QLineEdit(self.groupBox)
        self.updateIDNumber.setGeometry(QtCore.QRect(180, 40, 181, 40))
        self.updateIDNumber.setObjectName("updateIDNumber")
        self.updateFirstName = QtWidgets.QLineEdit(self.groupBox)
        self.updateFirstName.setGeometry(QtCore.QRect(182, 90, 181, 41))
        self.updateFirstName.setObjectName("updateFirstName")
        self.updateLastName = QtWidgets.QLineEdit(self.groupBox)
        self.updateLastName.setGeometry(QtCore.QRect(182, 140, 181, 41))
        self.updateLastName.setObjectName("updateLastName")
        self.updateYearLevelComboBox = QtWidgets.QComboBox(self.groupBox)
        self.updateYearLevelComboBox.setGeometry(QtCore.QRect(180, 190, 181, 41))
        self.updateYearLevelComboBox.setObjectName("updateYearLevelComboBox")
        self.updateYearLevelComboBox.addItem("")
        self.updateYearLevelComboBox.addItem("")
        self.updateYearLevelComboBox.addItem("")
        self.updateYearLevelComboBox.addItem("")
        self.updateGenderComboBox = QtWidgets.QComboBox(self.groupBox)
        self.updateGenderComboBox.setGeometry(QtCore.QRect(180, 240, 181, 41))
        self.updateGenderComboBox.setObjectName("updateGenderComboBox")
        self.updateGenderComboBox.addItem("")
        self.updateGenderComboBox.addItem("")
        self.updateProgramCodeComboBox = QtWidgets.QComboBox(self.groupBox)
        self.updateProgramCodeComboBox.setGeometry(QtCore.QRect(180, 290, 181, 41))
        self.updateProgramCodeComboBox.setObjectName("updateProgramCodeComboBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 161, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 161, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 161, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 190, 161, 41))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 240, 161, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 290, 161, 41))
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(230, 370, 130, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 370, 130, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 371, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.updateYearLevelComboBox.setItemText(0, _translate("Dialog", "1"))
        self.updateYearLevelComboBox.setItemText(1, _translate("Dialog", "2"))
        self.updateYearLevelComboBox.setItemText(2, _translate("Dialog", "3"))
        self.updateYearLevelComboBox.setItemText(3, _translate("Dialog", "4"))
        self.updateGenderComboBox.setItemText(0, _translate("Dialog", "M"))
        self.updateGenderComboBox.setItemText(1, _translate("Dialog", "F"))
        self.label_2.setText(_translate("Dialog", "ID Number"))
        self.label_3.setText(_translate("Dialog", "First Name"))
        self.label_4.setText(_translate("Dialog", "Last Name:"))
        self.label_5.setText(_translate("Dialog", "Year Level:"))
        self.label_6.setText(_translate("Dialog", "Gender:"))
        self.label_7.setText(_translate("Dialog", "Program Code:"))
        self.pushButton.setText(_translate("Dialog", "Edit"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
        self.label.setText(_translate("Dialog", "UPDATE STUDENT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
