# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updateCollege.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CollegeDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(489, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 20, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 191, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 201, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.collegeCodeEdit = QtWidgets.QLineEdit(Dialog)
        self.collegeCodeEdit.setGeometry(QtCore.QRect(220, 90, 251, 41))
        self.collegeCodeEdit.setObjectName("collegeCodeEdit")
        self.collegeNameEdit = QtWidgets.QLineEdit(Dialog)
        self.collegeNameEdit.setGeometry(QtCore.QRect(220, 150, 251, 41))
        self.collegeNameEdit.setObjectName("collegeNameEdit")
        self.confirmButton = QtWidgets.QPushButton(Dialog)
        self.confirmButton.setGeometry(QtCore.QRect(250, 230, 130, 40))
        self.confirmButton.setObjectName("confirmButton")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(90, 230, 130, 40))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Update College"))
        self.label.setText(_translate("Dialog", "UPDATE COLLEGE"))
        self.label_2.setText(_translate("Dialog", "COLLEGE CODE:"))
        self.label_3.setText(_translate("Dialog", "COLLEGE NAME:"))
        self.confirmButton.setText(_translate("Dialog", "Confirm"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_CollegeDialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
