# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updateProgram.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProgramDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(474, 333)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 10, 371, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 191, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 191, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 191, 41))
        self.label_4.setObjectName("label_4")
        self.programCodeEdit = QtWidgets.QLineEdit(Dialog)
        self.programCodeEdit.setGeometry(QtCore.QRect(220, 80, 241, 41))
        self.programCodeEdit.setObjectName("programCodeEdit")
        self.programNameEdit = QtWidgets.QLineEdit(Dialog)
        self.programNameEdit.setGeometry(QtCore.QRect(220, 140, 241, 41))
        self.programNameEdit.setObjectName("programNameEdit")
        self.collegeCodeBox = QtWidgets.QComboBox(Dialog)
        self.collegeCodeBox.setGeometry(QtCore.QRect(220, 200, 241, 41))
        self.collegeCodeBox.setObjectName("collegeCodeBox")
        self.confirmButton = QtWidgets.QPushButton(Dialog)
        self.confirmButton.setGeometry(QtCore.QRect(240, 260, 130, 40))
        self.confirmButton.setObjectName("confirmButton")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(80, 260, 130, 40))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "UPDATE PROGRAM"))
        self.label_2.setText(_translate("Dialog", "PROGRAM CODE:"))
        self.label_3.setText(_translate("Dialog", "PROGRAM NAME:"))
        self.label_4.setText(_translate("Dialog", "COLLEGE CODE:"))
        self.confirmButton.setText(_translate("Dialog", "Confirm"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_ProgramDialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
