# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updateProgram.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProgramDialog(object):
    def setupUi(self, ProgramDialog):
        ProgramDialog.setObjectName("ProgramDialog")
        ProgramDialog.resize(474, 333)
        self.label = QtWidgets.QLabel(ProgramDialog)
        self.label.setGeometry(QtCore.QRect(50, 10, 371, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ProgramDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 211, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ProgramDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 211, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ProgramDialog)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 201, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.programCodeEdit = QtWidgets.QLineEdit(ProgramDialog)
        self.programCodeEdit.setGeometry(QtCore.QRect(220, 80, 241, 41))
        self.programCodeEdit.setObjectName("programCodeEdit")
        self.programNameEdit = QtWidgets.QLineEdit(ProgramDialog)
        self.programNameEdit.setGeometry(QtCore.QRect(220, 140, 241, 41))
        self.programNameEdit.setObjectName("programNameEdit")
        self.collegeCodeBox = QtWidgets.QComboBox(ProgramDialog)
        self.collegeCodeBox.setGeometry(QtCore.QRect(220, 200, 241, 41))
        self.collegeCodeBox.setObjectName("collegeCodeBox")
        self.confirmButton = QtWidgets.QPushButton(ProgramDialog)
        self.confirmButton.setGeometry(QtCore.QRect(240, 260, 130, 40))
        self.confirmButton.setObjectName("confirmButton")
        self.cancelButton = QtWidgets.QPushButton(ProgramDialog)
        self.cancelButton.setGeometry(QtCore.QRect(80, 260, 130, 40))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(ProgramDialog)
        QtCore.QMetaObject.connectSlotsByName(ProgramDialog)

    def retranslateUi(self, ProgramDialog):
        _translate = QtCore.QCoreApplication.translate
        ProgramDialog.setWindowTitle(_translate("ProgramDialog", "Update Program"))
        self.label.setText(_translate("ProgramDialog", "UPDATE PROGRAM"))
        self.label_2.setText(_translate("ProgramDialog", "Program Code:"))
        self.label_3.setText(_translate("ProgramDialog", "Program Name:"))
        self.label_4.setText(_translate("ProgramDialog", "College Code:"))
        self.confirmButton.setText(_translate("ProgramDialog", "Confirm"))
        self.cancelButton.setText(_translate("ProgramDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProgramDialog = QtWidgets.QDialog()
    ui = Ui_ProgramDialog()
    ui.setupUi(ProgramDialog)
    ProgramDialog.show()
    sys.exit(app.exec_())
