# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updateCollege.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CollegeDialog(object):
    def setupUi(self, CollegeDialog):
        CollegeDialog.setObjectName("CollegeDialog")
        CollegeDialog.resize(489, 300)
        self.label = QtWidgets.QLabel(CollegeDialog)
        self.label.setGeometry(QtCore.QRect(80, 20, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(CollegeDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(CollegeDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.collegeCodeEdit = QtWidgets.QLineEdit(CollegeDialog)
        self.collegeCodeEdit.setGeometry(QtCore.QRect(220, 90, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.collegeCodeEdit.setFont(font)
        self.collegeCodeEdit.setObjectName("collegeCodeEdit")
        self.collegeNameEdit = QtWidgets.QLineEdit(CollegeDialog)
        self.collegeNameEdit.setGeometry(QtCore.QRect(220, 150, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.collegeNameEdit.setFont(font)
        self.collegeNameEdit.setObjectName("collegeNameEdit")
        self.confirmButton = QtWidgets.QPushButton(CollegeDialog)
        self.confirmButton.setGeometry(QtCore.QRect(250, 230, 130, 40))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.confirmButton.setFont(font)
        self.confirmButton.setObjectName("confirmButton")
        self.cancelButton = QtWidgets.QPushButton(CollegeDialog)
        self.cancelButton.setGeometry(QtCore.QRect(90, 230, 130, 40))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(CollegeDialog)
        QtCore.QMetaObject.connectSlotsByName(CollegeDialog)

    def retranslateUi(self, CollegeDialog):
        _translate = QtCore.QCoreApplication.translate
        CollegeDialog.setWindowTitle(_translate("CollegeDialog", "Update College"))
        self.label.setText(_translate("CollegeDialog", "Update College"))
        self.label_2.setText(_translate("CollegeDialog", "College Code:"))
        self.label_3.setText(_translate("CollegeDialog", "College Name:"))
        self.confirmButton.setText(_translate("CollegeDialog", "Confirm"))
        self.cancelButton.setText(_translate("CollegeDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CollegeDialog = QtWidgets.QDialog()
    ui = Ui_CollegeDialog()
    ui.setupUi(CollegeDialog)
    CollegeDialog.show()
    sys.exit(app.exec_())
